In [81]:
import math

a = 2
b = 3
r = 20

#The lower this value the higher quality the circle is with more points generated
stepSize = 0.01

#Generated vertices
positions = []

t = 0
while t < 2 * math.pi:
    positions.append((r * math.cos(t) + a, r * math.sin(t) + b,0.6))
    t += stepSize

print(len(positions))

629


In [ ]:
import numpy as np
import numpy as np
from scipy.interpolate import make_interp_spline
import matplotlib.pyplot as plt
import pickle

# Dataset
x = np.array([-10, -5, 5, 10])
y = np.array([ 0, 2, 2, 0])

X_Y_Spline = make_interp_spline(x, y)

# Returns evenly spaced numbers
# over a specified interval.
X_ = np.linspace(x.min(), x.max(), 30)
Y_ = X_Y_Spline(X_)

x1=np.linspace(-25,-10,30)
x2=np.linspace(10,25,30)
y0=np.zeros(30)

xf1=np.append(x1,X_)
yf2=np.append(y0,Y_)

xf=np.append(xf1,x2)
yf=np.append(yf2,y0)


zf=np.full(len(xf),0.6)
lst=list(zip(xf,yf,zf))
final=list(set([i for i in lst]))
#final1 = np.asarray([ list(a) for a in final])

print(final)
print(len(final))
print(len(xf))
print(len(yf))

# Plotting the Graph
plt.plot(xf, yf)
plt.title("Plot Smooth Curve Using the scipy.interpolate.make_interp_spline() Class")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()


In [41]:
import numpy as np
import numpy as np
from scipy.interpolate import make_interp_spline
import matplotlib.pyplot as plt
import pickle

In [42]:
with open('/home/santhanam.17/Carla_scripts/point_cloud_database_main_optimized.pickle', 'rb') as handle:
    read_dict = pickle.load(handle)

In [72]:
keys=list(read_dict.keys())
print(keys[10000])

(32.0, 1.9594349641362686e-15, 0.1478431224822998, 100.0, 32)


In [43]:
def closest_point(arr, orr):
    Ego_postion=np.array([0,0,0])
    dist = round(np.linalg.norm(arr - Ego_postion))
    lst=list(range(-180,180,1))
    closet_yaw_rate=lst[min(range(len(lst)), key = lambda i: abs(lst[i]-orr))]
    closest_keys=[k for k in keys if k[4]==dist and k[3]==closet_yaw_rate ]
    closest_points_with_yaw=np.array([[key[0],key[1],key[2],key[3]] for key in closest_keys])
    #rospy.loginfo(closest_points_with_yaw)
    closest_points=np.array([[key[0],key[1],key[2]] for key in closest_keys])
    dist_2 = np.sum((closest_points - arr)**2, axis=1)
    #rospy.loginfo(closest_points[np.argmin(dist_2)])
    closest_key=closest_points_with_yaw[np.argmin(dist_2)]
    closest_key=np.append(closest_key,dist)

    pcd=read_dict[tuple(list(closest_key))]
    
    """rospy.loginfo(np.linalg.norm(arr - Ego_postion))
    rospy.loginfo(dist)
    rospy.loginfo(tuple(list(closest_key)))
    rospy.loginfo(pcd)"""
    #rospy.loginfo(len(closest_points))
    return pcd

In [66]:
arr=np.array([120,30,0])
orr=90

Ego_postion=np.array([0,0,0])
dist = round(np.linalg.norm(arr - Ego_postion))
if dist>=120:
    dist=120
lst=list(range(-180,180,1))
closet_yaw_rate=lst[min(range(len(lst)), key = lambda i: abs(lst[i]-orr))]
closest_keys=[k for k in keys if k[4]==dist and k[3]==closet_yaw_rate ]
"""closest_points_with_yaw=np.array([[key[0],key[1],key[2],key[3]] for key in closest_keys])
#rospy.loginfo(closest_points_with_yaw)
closest_points=np.array([[key[0],key[1],key[2]] for key in closest_keys])
dist_2 = np.sum((closest_points - arr)**2, axis=1)
#rospy.loginfo(closest_points[np.argmin(dist_2)])
closest_key=closest_points_with_yaw[np.argmin(dist_2)]
closest_key=np.append(closest_key,dist)"""

pcd=read_dict[closest_keys[0]]
#print(pcd)
print(dist)
print(closet_yaw_rate)
print(closest_keys)
print(read_dict[closest_keys[0]])

120
90
[(120.0, 7.347880374357178e-15, 0.14402392506599426, 90.0, 120)]
[[ 7.10418312e-315  0.00000000e+000  6.21648314e-310]
 [ 1.19784363e+002 -3.18016797e-001 -9.95557845e-001]
 [ 1.19268639e+002 -2.19234991e+000 -1.98302293e+000]
 [ 1.19114258e+002 -1.81480002e+000 -1.98035085e+000]
 [ 1.19094810e+002 -1.43988883e+000 -1.97994292e+000]
 [ 1.19349991e+002 -1.06758547e+000 -1.98411953e+000]
 [ 1.19087273e+002 -6.90693855e-001 -1.97970605e+000]
 [ 1.19089256e+002 -3.16171378e-001 -1.97971261e+000]
 [ 1.19094498e+002  5.83589450e-002 -1.97979331e+000]
 [ 1.19101677e+002  4.32962269e-001 -1.97992551e+000]
 [ 1.19109932e+002  8.07594001e-001 -1.98009491e+000]
 [ 1.19094810e+002  1.18206310e+000 -1.97989559e+000]
 [ 1.19094810e+002  1.55665755e+000 -1.97996736e+000]
 [ 1.19129883e+002  1.93185174e+000 -1.98064148e+000]
 [ 1.19447716e+002  2.31277871e+000 -1.98603666e+000]
 [ 1.19818253e+002 -2.40598202e-001 -9.95837867e-001]
 [ 1.19219040e+002 -2.11321306e+000 -1.98217463e+000]
 [ 1.19349